### ISSUE TITLE
error deleting flow

### ISSUE THREAD

**Issue by tobiasdam** [lorabridge2/gateway-flow-manager#13]
```python
[[<action_bytes.REMOVE_FLOW: 11>, 67]]
Traceback (most recent call last):
  File "/home/devman/flowman.py", line 820, in <module>
    main()
  File "/home/devman/flowman.py", line 133, in main
    process_flow(flow, r_client)
  File "/home/devman/flowman.py", line 295, in process_flow
    r_client.delete([REDIS_PREFIX, COMMANDS_PREFIX, flow["id"]])
  File "/usr/local/lib/python3.11/site-packages/redis/commands/core.py", line 1704, in delete
    return self.execute_command("DEL", *names)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 548, in execute_command
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 549, in <lambda>
    lambda: self._send_command_parse_response(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 524, in _send_command_parse_response
    conn.send_command(*args)
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 477, in send_command
    self._command_packer.pack(*args),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 97, in pack
    for arg in map(self.encode, args):
  File "/usr/local/lib/python3.11/site-packages/redis/_parsers/encoders.py", line 29, in encode
    raise DataError(
redis.exceptions.DataError: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
```

**Comment by tobiasdam** [comment]
fixed
